export const ADD_LEADERS_CARDS = 'ADD_LEADERS_CARDS';
export const ADD_CARDS = 'ADD_CARDS';
export const ADD_FILTERED_CARDS = 'ADD_FILTERED_CARDS';
export const GET_FILTERS_CARDS = 'GET_FILTERS_CARDS';
export const ADD_FILTERS_LEADERS = 'ADD_FILTERS_LEADERS';
export const SET_SELECT_LEADER = 'SET_SELECT_LEADER';
export const EDIT_DECK = 'EDIT_DECK';
